export const LANGUAGE_OPTIONS = [
  { value: 'python', label: 'Python' },
  { value: 'python_questions', label: 'Python (questions)' },
  { value: 'asyncio', label: 'Asyncio' },
  { value: 'graphql', label: 'GraphQL' },
  { value: 'security', label: 'Security' },
  { value: 'pandas', label: 'Pandas' },
  { value: 'langchain_langgraph', label: 'LangChain/LangGraph' },
  { value: 'machine_learning', label: 'Machine Learning' },
  { value: 'python_theory', label: 'Python (theory)' },
  { value: 'fastapi', label: 'FastAPI' },
  { value: 'django', label: 'Django' },
  { value: 'react', label: 'React' },
  { value: 'javascript', label: 'JavaScript' },
  { value: 'sql', label: 'SQL' },
];
