from app.models import Issue, Severity, Task

TASKS = [
    Task(
        id="task-1",
        title="Add endpoint to create orders",
        description="This endpoint allows users to create an order. Basic functionality implemented.",
        requirements=[
            "Validate user input",
            "Ensure total price correctness",
            "Handle errors properly",
            "Follow clean architecture practices",
        ],
        instructions=[
            "Review the code",
            "Add inline comments",
            "Explain impact and risk",
            "Suggest improvements",
            "(Optional) Provide fixed code",
        ],
        language="python",
        code="""from fastapi import APIRouter\n\nrouter = APIRouter()\n\n@router.post('/orders')\ndef create_order(payload: dict):\n    items = payload.get('items', [])\n    user_id = payload.get('user_id')\n\n    total = 0\n    for item in items:\n        total += item.get('price', 0) * item.get('qty', 1)\n\n    order = {\n        'user_id': user_id,\n        'items': items,\n        'total': payload.get('total'),\n    }\n\n    # Simulate save\n    return {'ok': True, 'order': order}\n""",
        reference_issues=[
            Issue(
                id="i-1",
                line=6,
                severity=Severity.critical,
                title="Missing payload validation",
                description="Endpoint accepts unvalidated dict; malformed payload can pass through.",
                suggestion="Use a Pydantic request model and enforce required fields.",
            ),
            Issue(
                id="i-2",
                line=16,
                severity=Severity.critical,
                title="Total price is not verified",
                description="Computed total is ignored and client-provided total is trusted.",
                suggestion="Compare computed total with payload total and reject mismatch.",
            ),
            Issue(
                id="i-3",
                line=19,
                severity=Severity.medium,
                title="No error handling",
                description="Function never raises explicit HTTP errors for invalid data.",
                suggestion="Return proper 4xx responses for validation and business rule failures.",
            ),
            Issue(
                id="i-4",
                line=5,
                severity=Severity.low,
                title="Layering/architecture concern",
                description="Endpoint contains business logic directly in route handler.",
                suggestion="Move order calculation and validation into a service layer.",
            ),
        ],
    ),
    Task(
        id="task-2",
        title="Add endpoint to update user profile",
        description="Patch endpoint to update user profile fields. Basic update behavior is implemented.",
        requirements=[
            "Validate allowed fields",
            "Prevent unauthorized updates",
            "Handle missing users safely",
            "Avoid leaking internal errors",
        ],
        instructions=[
            "Review the code",
            "Add inline comments",
            "Explain impact and risk",
            "Suggest improvements",
            "(Optional) Provide fixed code",
        ],
        language="python",
        code="""from fastapi import APIRouter\n\nrouter = APIRouter()\n\nFAKE_DB = {'1': {'name': 'Ann', 'role': 'user', 'email': 'ann@mail.com'}}\n\n@router.patch('/users/{user_id}')\ndef update_profile(user_id: str, payload: dict, actor_id: str):\n    user = FAKE_DB.get(user_id)\n\n    for key, value in payload.items():\n        user[key] = value\n\n    if actor_id != user_id:\n        return {'ok': False, 'error': 'forbidden'}\n\n    return {'ok': True, 'user': user}\n""",
        reference_issues=[
            Issue(
                id="t2-i1",
                line=11,
                severity=Severity.critical,
                title="Authorization check happens too late",
                description="User record is modified before verifying actor identity.",
                suggestion="Check authorization before applying any update.",
            ),
            Issue(
                id="t2-i2",
                line=8,
                severity=Severity.critical,
                title="Missing null handling for user",
                description="When user is not found, code will crash when iterating updates.",
                suggestion="Return 404 when user does not exist.",
            ),
            Issue(
                id="t2-i3",
                line=10,
                severity=Severity.medium,
                title="No field whitelist",
                description="Payload can overwrite protected fields like role.",
                suggestion="Validate payload keys against an allowed set.",
            ),
            Issue(
                id="t2-i4",
                line=12,
                severity=Severity.low,
                title="Inconsistent API error shape",
                description="Returns business error as 200 payload instead of proper HTTP status.",
                suggestion="Raise HTTPException with status 403 and stable error format.",
            ),
        ],
    ),
    Task(
        id="task-3",
        title="Add endpoint to upload invoice",
        description="Endpoint accepts invoice file metadata and stores it for later processing.",
        requirements=[
            "Validate file type and size",
            "Sanitize user-provided names",
            "Handle storage failures",
            "Preserve clean separation of concerns",
        ],
        instructions=[
            "Review the code",
            "Add inline comments",
            "Explain impact and risk",
            "Suggest improvements",
            "(Optional) Provide fixed code",
        ],
        language="python",
        code="""from fastapi import APIRouter\nimport os\n\nrouter = APIRouter()\n\n@router.post('/invoices/upload')\ndef upload_invoice(payload: dict):\n    filename = payload.get('filename', 'invoice.txt')\n    content = payload.get('content', '')\n\n    path = f"/tmp/uploads/{filename}"\n    with open(path, 'w') as f:\n        f.write(content)\n\n    return {'ok': True, 'path': path}\n""",
        reference_issues=[
            Issue(
                id="t3-i1",
                line=10,
                severity=Severity.critical,
                title="Path traversal risk",
                description="User-controlled filename is used directly in filesystem path.",
                suggestion="Normalize and validate filename; reject unsafe path segments.",
            ),
            Issue(
                id="t3-i2",
                line=11,
                severity=Severity.critical,
                title="No size limit enforcement",
                description="Large payload content can exhaust disk or memory resources.",
                suggestion="Validate max payload/file size before write.",
            ),
            Issue(
                id="t3-i3",
                line=11,
                severity=Severity.medium,
                title="No error handling for I/O",
                description="File write exceptions are not caught or translated to API errors.",
                suggestion="Handle OSError and return a meaningful server error response.",
            ),
            Issue(
                id="t3-i4",
                line=2,
                severity=Severity.low,
                title="Unused import",
                description="Module imports os but does not use it.",
                suggestion="Remove unused imports to keep code clean.",
            ),
        ],
    ),
    Task(
        id="task-4",
        title="Add endpoint to list payments",
        description="List API for payments with filtering and sorting support.",
        requirements=[
            "Validate query params",
            "Avoid mutating shared state",
            "Implement safe pagination",
            "Return consistent response schema",
        ],
        instructions=[
            "Review the code",
            "Add inline comments",
            "Explain impact and risk",
            "Suggest improvements",
            "(Optional) Provide fixed code",
        ],
        language="python",
        code="""from fastapi import APIRouter\n\nrouter = APIRouter()\n\nPAYMENTS = [\n    {'id': 1, 'amount': 100, 'status': 'ok'},\n    {'id': 2, 'amount': 450, 'status': 'failed'},\n    {'id': 3, 'amount': 70, 'status': 'ok'},\n]\n\n@router.get('/payments')\ndef list_payments(sort: str = 'amount', limit: int = 1000):\n    PAYMENTS.sort(key=lambda x: x[sort])\n    return {'items': PAYMENTS[:limit], 'count': len(PAYMENTS)}\n""",
        reference_issues=[
            Issue(
                id="t4-i1",
                line=12,
                severity=Severity.critical,
                title="Unvalidated dynamic sort key",
                description="Attacker can pass unknown key and trigger runtime errors.",
                suggestion="Validate sort against an allowed set of fields.",
            ),
            Issue(
                id="t4-i2",
                line=12,
                severity=Severity.medium,
                title="Mutates global shared state",
                description="In-place sort mutates PAYMENTS and can cause cross-request side effects.",
                suggestion="Sort a copy instead of mutating the module-level list.",
            ),
            Issue(
                id="t4-i3",
                line=11,
                severity=Severity.medium,
                title="Unsafe default pagination",
                description="Very large default limit can degrade performance.",
                suggestion="Use conservative default and enforce max limit.",
            ),
            Issue(
                id="t4-i4",
                line=13,
                severity=Severity.low,
                title="Count semantics unclear",
                description="Count returns total data length, not filtered/page size context.",
                suggestion="Return total and page_count fields explicitly.",
            ),
        ],
    ),
    Task(
        id="task-5",
        title="Add endpoint to delete project",
        description="Delete API for projects and associated metadata cleanup.",
        requirements=[
            "Authorize destructive action",
            "Use safe deletion semantics",
            "Handle missing project",
            "Avoid broad exception swallowing",
        ],
        instructions=[
            "Review the code",
            "Add inline comments",
            "Explain impact and risk",
            "Suggest improvements",
            "(Optional) Provide fixed code",
        ],
        language="python",
        code="""from fastapi import APIRouter\n\nrouter = APIRouter()\nPROJECTS = {'p1': {'owner': 'u1'}, 'p2': {'owner': 'u2'}}\n\n@router.delete('/projects/{project_id}')\ndef delete_project(project_id: str, actor_id: str):\n    try:\n        project = PROJECTS[project_id]\n        if project['owner'] != actor_id:\n            return {'ok': False}\n        del PROJECTS[project_id]\n        return {'ok': True}\n    except Exception:\n        return {'ok': True}\n""",
        reference_issues=[
            Issue(
                id="t5-i1",
                line=13,
                severity=Severity.critical,
                title="Swallows all exceptions and returns success",
                description="Failures and missing project cases are hidden behind ok=true.",
                suggestion="Handle KeyError/expected errors explicitly and return correct status.",
            ),
            Issue(
                id="t5-i2",
                line=9,
                severity=Severity.critical,
                title="Authorization failure returned as success status",
                description="Unauthorized delete returns plain payload instead of HTTP 403.",
                suggestion="Raise HTTPException(403) for forbidden access.",
            ),
            Issue(
                id="t5-i3",
                line=8,
                severity=Severity.medium,
                title="Missing not-found handling",
                description="PROJECTS[project_id] raises if id is missing; no clear 404 behavior.",
                suggestion="Return 404 when project is not found.",
            ),
            Issue(
                id="t5-i4",
                line=7,
                severity=Severity.low,
                title="No audit trail for destructive action",
                description="Deletion events are not logged for traceability.",
                suggestion="Emit a structured audit log before and after deletion.",
            ),
        ],
    ),
]
