from app.models import Issue, Severity, Task

TASKS = [
    # == 1. Web: Create orders ==
    Task(
        id="task-1",
        title="Add endpoint to create orders",
        description="This endpoint allows users to create an order. Basic functionality implemented.",
        requirements=["Validate user input", "Ensure total price correctness", "Handle errors properly", "Follow clean architecture practices"],
        instructions=["Review the code", "Add inline comments", "Explain impact and risk", "Suggest improvements", "(Optional) Provide fixed code"],
        language="python",
        code="from fastapi import APIRouter\n\nrouter = APIRouter()\n\n@router.post(\'/orders\')\ndef create_order(payload: dict):\n    items = payload.get(\'items\', [])\n    user_id = payload.get(\'user_id\')\n\n    total = 0\n    for item in items:\n        total += item.get(\'price\', 0) * item.get(\'qty\', 1)\n\n    order = {\n        \'user_id\': user_id,\n        \'items\': items,\n        \'total\': payload.get(\'total\'),\n    }\n\n    # Simulate save\n    return {\'ok\': True, \'order\': order}\n",
        reference_issues=[
            Issue(id="i-1", line=6, severity=Severity.critical, title="Missing payload validation", description="Endpoint accepts unvalidated dict; malformed payload can pass through.", suggestion="Use a Pydantic request model and enforce required fields."),
            Issue(id="i-2", line=17, severity=Severity.critical, title="Total price is not verified", description="Computed total is ignored and client-provided total is trusted.", suggestion="Compare computed total with payload total and reject mismatch."),
            Issue(id="i-3", line=20, severity=Severity.medium, title="No error handling", description="Function never raises explicit HTTP errors for invalid data.", suggestion="Return proper 4xx responses for validation and business rule failures."),
            Issue(id="i-4", line=5, severity=Severity.low, title="Layering/architecture concern", description="Endpoint contains business logic directly in route handler.", suggestion="Move order calculation and validation into a service layer."),
        ],
    ),
    # == 2. Web: Update user profile ==
    Task(
        id="task-2",
        title="Add endpoint to update user profile",
        description="Patch endpoint to update user profile fields. Basic update behavior is implemented.",
        requirements=["Validate allowed fields", "Prevent unauthorized updates", "Handle missing users safely", "Avoid leaking internal errors"],
        instructions=["Review the code", "Add inline comments", "Explain impact and risk", "Suggest improvements", "(Optional) Provide fixed code"],
        language="python",
        code="from fastapi import APIRouter\n\nrouter = APIRouter()\n\nFAKE_DB = {\'1\': {\'name\': \'Ann\', \'role\': \'user\', \'email\': \'ann@mail.com\'}}\n\n@router.patch(\'/users/{user_id}\')\ndef update_profile(user_id: str, payload: dict, actor_id: str):\n    user = FAKE_DB.get(user_id)\n\n    for key, value in payload.items():\n        user[key] = value\n\n    if actor_id != user_id:\n        return {\'ok\': False, \'error\': \'forbidden\'}\n\n    return {\'ok\': True, \'user\': user}\n",
        reference_issues=[
            Issue(id="t2-i1", line=11, severity=Severity.critical, title="Authorization check happens too late", description="User record is modified before verifying actor identity.", suggestion="Check authorization before applying any update."),
            Issue(id="t2-i2", line=8, severity=Severity.critical, title="Missing null handling for user", description="When user is not found, code will crash when iterating updates.", suggestion="Return 404 when user does not exist."),
            Issue(id="t2-i3", line=11, severity=Severity.medium, title="No field whitelist", description="Payload can overwrite protected fields like role.", suggestion="Validate payload keys against an allowed set."),
            Issue(id="t2-i4", line=15, severity=Severity.low, title="Inconsistent API error shape", description="Returns business error as 200 payload instead of proper HTTP status.", suggestion="Raise HTTPException with status 403 and stable error format."),
        ],
    ),
    # == 3. Web: Upload invoice ==
    Task(
        id="task-3",
        title="Add endpoint to upload invoice",
        description="Endpoint accepts invoice file metadata and stores it for later processing.",
        requirements=["Validate file type and size", "Sanitize user-provided names", "Handle storage failures", "Preserve clean separation of concerns"],
        instructions=["Review the code", "Add inline comments", "Explain impact and risk", "Suggest improvements", "(Optional) Provide fixed code"],
        language="python",
        code="from fastapi import APIRouter\nimport os\n\nrouter = APIRouter()\n\n@router.post(\'/invoices/upload\')\ndef upload_invoice(payload: dict):\n    filename = payload.get(\'filename\', \'invoice.txt\')\n    content = payload.get(\'content\', \'\')\n\n    path = f\"/tmp/uploads/{filename}\"\n    with open(path, \'w\') as f:\n        f.write(content)\n\n    return {\'ok\': True, \'path\': path}\n",
        reference_issues=[
            Issue(id="t3-i1", line=11, severity=Severity.critical, title="Path traversal risk", description="User-controlled filename is used directly in filesystem path.", suggestion="Normalize and validate filename; reject unsafe path segments."),
            Issue(id="t3-i2", line=12, severity=Severity.critical, title="No size limit enforcement", description="Large payload content can exhaust disk or memory resources.", suggestion="Validate max payload/file size before write."),
            Issue(id="t3-i3", line=12, severity=Severity.medium, title="No error handling for I/O", description="File write exceptions are not caught or translated to API errors.", suggestion="Handle OSError and return a meaningful server error response."),
            Issue(id="t3-i4", line=2, severity=Severity.low, title="Unused import", description="Module imports os but does not use it.", suggestion="Remove unused imports to keep code clean."),
        ],
    ),
    # == 4. Web: List payments ==
    Task(
        id="task-4",
        title="Add endpoint to list payments",
        description="List API for payments with filtering and sorting support.",
        requirements=["Validate query params", "Avoid mutating shared state", "Implement safe pagination", "Return consistent response schema"],
        instructions=["Review the code", "Add inline comments", "Explain impact and risk", "Suggest improvements", "(Optional) Provide fixed code"],
        language="python",
        code="from fastapi import APIRouter\n\nrouter = APIRouter()\n\nPAYMENTS = [\n    {\'id\': 1, \'amount\': 100, \'status\': \'ok\'},\n    {\'id\': 2, \'amount\': 450, \'status\': \'failed\'},\n    {\'id\': 3, \'amount\': 70, \'status\': \'ok\'},\n]\n\n@router.get(\'/payments\')\ndef list_payments(sort: str = \'amount\', limit: int = 1000):\n    PAYMENTS.sort(key=lambda x: x[sort])\n    return {\'items\': PAYMENTS[:limit], \'count\': len(PAYMENTS)}\n",
        reference_issues=[
            Issue(id="t4-i1", line=13, severity=Severity.critical, title="Unvalidated dynamic sort key", description="Attacker can pass unknown key and trigger runtime errors.", suggestion="Validate sort against an allowed set of fields."),
            Issue(id="t4-i2", line=13, severity=Severity.medium, title="Mutates global shared state", description="In-place sort mutates PAYMENTS and can cause cross-request side effects.", suggestion="Sort a copy instead of mutating the module-level list."),
            Issue(id="t4-i3", line=12, severity=Severity.medium, title="Unsafe default pagination", description="Very large default limit can degrade performance.", suggestion="Use conservative default and enforce max limit."),
            Issue(id="t4-i4", line=14, severity=Severity.low, title="Count semantics unclear", description="Count returns total data length, not filtered/page size context.", suggestion="Return total and page_count fields explicitly."),
        ],
    ),
    # == 5. Web: Delete project ==
    Task(
        id="task-5",
        title="Add endpoint to delete project",
        description="Delete API for projects and associated metadata cleanup.",
        requirements=["Authorize destructive action", "Use safe deletion semantics", "Handle missing project", "Avoid broad exception swallowing"],
        instructions=["Review the code", "Add inline comments", "Explain impact and risk", "Suggest improvements", "(Optional) Provide fixed code"],
        language="python",
        code="from fastapi import APIRouter\n\nrouter = APIRouter()\nPROJECTS = {\'p1\': {\'owner\': \'u1\'}, \'p2\': {\'owner\': \'u2\'}}\n\n@router.delete(\'/projects/{project_id}\')\ndef delete_project(project_id: str, actor_id: str):\n    try:\n        project = PROJECTS[project_id]\n        if project[\'owner\'] != actor_id:\n            return {\'ok\': False}\n        del PROJECTS[project_id]\n        return {\'ok\': True}\n    except Exception:\n        return {\'ok\': True}\n",
        reference_issues=[
            Issue(id="t5-i1", line=14, severity=Severity.critical, title="Swallows all exceptions and returns success", description="Failures and missing project cases are hidden behind ok=true.", suggestion="Handle KeyError/expected errors explicitly and return correct status."),
            Issue(id="t5-i2", line=10, severity=Severity.critical, title="Authorization failure returned as success status", description="Unauthorized delete returns plain payload instead of HTTP 403.", suggestion="Raise HTTPException(403) for forbidden access."),
            Issue(id="t5-i3", line=9, severity=Severity.medium, title="Missing not-found handling", description="PROJECTS[project_id] raises if id is missing; no clear 404 behavior.", suggestion="Return 404 when project is not found."),
            Issue(id="t5-i4", line=7, severity=Severity.low, title="No audit trail for destructive action", description="Deletion events are not logged for traceability.", suggestion="Emit a structured audit log before and after deletion."),
        ],
    ),
    # == 6. File processing: CSV reader ==
    Task(
        id="task-6",
        title="Parse CSV and aggregate sales by region",
        description="Script reads a CSV file of sales records and groups total revenue by region.",
        requirements=["Handle missing or malformed rows", "Close file handles properly", "Avoid loading entire file into memory", "Validate numeric fields"],
        instructions=["Review the code", "Add inline comments", "Explain impact and risk", "Suggest improvements", "(Optional) Provide fixed code"],
        language="python",
        code="import csv\n\ndef aggregate_sales(filepath):\n    results = {}\n    f = open(filepath)\n    reader = csv.DictReader(f)\n    for row in reader:\n        region = row[\'region\']\n        amount = float(row[\'amount\'])\n        results[region] = results.get(region, 0) + amount\n    return results\n",
        reference_issues=[
            Issue(id="t6-i1", line=5, severity=Severity.critical, title="File handle never closed", description="open() without context manager leaks file descriptors on error.", suggestion="Use 'with open(filepath) as f:' to ensure cleanup."),
            Issue(id="t6-i2", line=9, severity=Severity.medium, title="No error handling for invalid numbers", description="float() will raise ValueError on malformed data without a clear message.", suggestion="Wrap in try/except and skip or log bad rows."),
            Issue(id="t6-i3", line=8, severity=Severity.medium, title="Missing key access unguarded", description="KeyError raised if 'region' or 'amount' column is absent.", suggestion="Use row.get() with defaults or validate headers upfront."),
            Issue(id="t6-i4", line=3, severity=Severity.low, title="No type hints", description="Function signature does not document expected types.", suggestion="Add type hints: filepath: str -> dict[str, float]."),
        ],
    ),
    # == 7. Concurrency: Thread pool worker ==
    Task(
        id="task-7",
        title="Parallel URL fetcher with thread pool",
        description="Utility that fetches a list of URLs concurrently and returns responses.",
        requirements=["Handle request failures gracefully", "Limit concurrency", "Avoid shared-state bugs", "Set timeouts"],
        instructions=["Review the code", "Add inline comments", "Explain impact and risk", "Suggest improvements", "(Optional) Provide fixed code"],
        language="python",
        code="import requests\nfrom concurrent.futures import ThreadPoolExecutor\n\nresults = []\n\ndef fetch(url):\n    resp = requests.get(url)\n    results.append({\'url\': url, \'status\': resp.status_code})\n\ndef fetch_all(urls):\n    with ThreadPoolExecutor() as pool:\n        pool.map(fetch, urls)\n    return results\n",
        reference_issues=[
            Issue(id="t7-i1", line=4, severity=Severity.critical, title="Shared mutable global list", description="Multiple threads append to module-level list without synchronization; causes race conditions.", suggestion="Return values from fetch() and collect via pool.map(), or use a thread-safe structure."),
            Issue(id="t7-i2", line=7, severity=Severity.critical, title="No timeout on HTTP request", description="requests.get without timeout can hang indefinitely.", suggestion="Pass timeout=(connect, read) to requests.get()."),
            Issue(id="t7-i3", line=7, severity=Severity.medium, title="No exception handling for network errors", description="ConnectionError or Timeout will crash the entire pool.", suggestion="Wrap in try/except and return an error result."),
            Issue(id="t7-i4", line=11, severity=Severity.low, title="Unbounded thread pool", description="ThreadPoolExecutor() without max_workers can spawn too many threads.", suggestion="Set max_workers to a reasonable limit like 10."),
        ],
    ),
    # == 8. Data: JSON config loader ==
    Task(
        id="task-8",
        title="Load and merge application config from JSON",
        description="Reads a JSON config file and merges it with default settings.",
        requirements=["Handle missing file", "Validate config schema", "Avoid silent failures", "Protect sensitive values"],
        instructions=["Review the code", "Add inline comments", "Explain impact and risk", "Suggest improvements", "(Optional) Provide fixed code"],
        language="python",
        code="import json\n\nDEFAULTS = {\n    \'debug\': False,\n    \'db_url\': \'sqlite:///app.db\',\n    \'secret_key\': \'changeme\',\n    \'log_level\': \'INFO\',\n}\n\ndef load_config(path=\'config.json\'):\n    try:\n        with open(path) as f:\n            user_config = json.load(f)\n    except:\n        user_config = {}\n    DEFAULTS.update(user_config)\n    return DEFAULTS\n",
        reference_issues=[
            Issue(id="t8-i1", line=14, severity=Severity.critical, title="Bare except catches everything", description="Catches KeyboardInterrupt, SystemExit, and masks real errors like PermissionError.", suggestion="Catch FileNotFoundError and json.JSONDecodeError specifically."),
            Issue(id="t8-i2", line=16, severity=Severity.critical, title="Mutates module-level DEFAULTS", description="update() changes the global dict; subsequent calls return polluted config.", suggestion="Merge into a new dict: {**DEFAULTS, **user_config}."),
            Issue(id="t8-i3", line=6, severity=Severity.medium, title="Hardcoded secret key", description="Default secret_key 'changeme' may ship to production unnoticed.", suggestion="Require secret_key from environment or config; raise on missing."),
            Issue(id="t8-i4", line=13, severity=Severity.low, title="No schema validation", description="Arbitrary keys from user config are accepted without checking.", suggestion="Validate against allowed keys and types before merging."),
        ],
    ),
    # == 9. CLI: Batch file renamer ==
    Task(
        id="task-9",
        title="CLI tool to batch rename files",
        description="Script renames files in a directory by applying a prefix and converting to lowercase.",
        requirements=["Validate directory exists", "Avoid overwriting files", "Handle permission errors", "Provide dry-run mode"],
        instructions=["Review the code", "Add inline comments", "Explain impact and risk", "Suggest improvements", "(Optional) Provide fixed code"],
        language="python",
        code="import os\nimport sys\n\ndef rename_files(directory, prefix):\n    for name in os.listdir(directory):\n        new_name = prefix + name.lower()\n        os.rename(\n            os.path.join(directory, name),\n            os.path.join(directory, new_name),\n        )\n        print(f\'Renamed {name} -> {new_name}\')\n\nif __name__ == \'__main__\':\n    rename_files(sys.argv[1], sys.argv[2])\n",
        reference_issues=[
            Issue(id="t9-i1", line=6, severity=Severity.critical, title="No collision check before rename", description="If new_name already exists, os.rename silently overwrites on some systems.", suggestion="Check if destination exists and skip or error."),
            Issue(id="t9-i2", line=14, severity=Severity.critical, title="No argument validation", description="IndexError if user provides fewer than 2 arguments.", suggestion="Use argparse or check len(sys.argv) before accessing."),
            Issue(id="t9-i3", line=5, severity=Severity.medium, title="Renames directories too", description="os.listdir includes subdirectories; renaming them may break paths.", suggestion="Filter to files only with os.path.isfile()."),
            Issue(id="t9-i4", line=4, severity=Severity.low, title="No dry-run option", description="Cannot preview changes before applying destructive renames.", suggestion="Add a dry_run parameter that prints without renaming."),
        ],
    ),
    # == 10. Data: Database query builder ==
    Task(
        id="task-10",
        title="Build SQL query from user filters",
        description="Constructs a SELECT query based on dynamic filter parameters.",
        requirements=["Prevent SQL injection", "Validate filter fields", "Handle empty filters", "Support safe parameterization"],
        instructions=["Review the code", "Add inline comments", "Explain impact and risk", "Suggest improvements", "(Optional) Provide fixed code"],
        language="python",
        code="import sqlite3\n\ndef search_users(filters: dict):\n    conn = sqlite3.connect(\'app.db\')\n    query = \'SELECT * FROM users WHERE 1=1\'\n    for key, value in filters.items():\n        query += f\" AND {key} = \'{value}\'\"\n    cursor = conn.execute(query)\n    rows = cursor.fetchall()\n    return rows\n",
        reference_issues=[
            Issue(id="t10-i1", line=7, severity=Severity.critical, title="SQL injection via string interpolation", description="Both column name and value are injected directly into SQL string.", suggestion="Use parameterized queries with ? placeholders and whitelist column names."),
            Issue(id="t10-i2", line=4, severity=Severity.critical, title="Connection never closed", description="sqlite3 connection is opened but never closed; leaks resources.", suggestion="Use 'with conn:' or explicitly call conn.close() in a finally block."),
            Issue(id="t10-i3", line=6, severity=Severity.medium, title="No column whitelist", description="Arbitrary filter keys let users probe column names.", suggestion="Validate keys against an allowed set of column names."),
            Issue(id="t10-i4", line=9, severity=Severity.low, title="Returns raw tuples", description="fetchall returns tuples without column names; hard to use.", suggestion="Set row_factory = sqlite3.Row or return dicts."),
        ],
    ),
    # == 11. Security: Password hashing ==
    Task(
        id="task-11",
        title="User registration with password storage",
        description="Registers a new user and stores their password for later authentication.",
        requirements=["Hash passwords securely", "Prevent timing attacks", "Validate input", "Handle duplicates"],
        instructions=["Review the code", "Add inline comments", "Explain impact and risk", "Suggest improvements", "(Optional) Provide fixed code"],
        language="python",
        code="import hashlib\n\nUSERS = {}\n\ndef register(username, password):\n    if username in USERS:\n        return False\n    hashed = hashlib.md5(password.encode()).hexdigest()\n    USERS[username] = hashed\n    return True\n\ndef login(username, password):\n    hashed = hashlib.md5(password.encode()).hexdigest()\n    if USERS.get(username) == hashed:\n        return True\n    return False\n",
        reference_issues=[
            Issue(id="t11-i1", line=8, severity=Severity.critical, title="MD5 is not a password hash", description="MD5 is fast and broken; trivially cracked with rainbow tables.", suggestion="Use bcrypt, argon2, or hashlib.pbkdf2_hmac with a unique salt."),
            Issue(id="t11-i2", line=8, severity=Severity.critical, title="No salt used", description="Identical passwords produce identical hashes; enables precomputation attacks.", suggestion="Generate a random salt per user and store alongside the hash."),
            Issue(id="t11-i3", line=14, severity=Severity.medium, title="Timing attack on comparison", description="== comparison leaks password hash length via timing side channel.", suggestion="Use hmac.compare_digest() for constant-time comparison."),
            Issue(id="t11-i4", line=5, severity=Severity.low, title="No input validation", description="Empty username or password is accepted without error.", suggestion="Validate minimum length and disallow empty values."),
        ],
    ),
    # == 12. Caching: LRU cache implementation ==
    Task(
        id="task-12",
        title="Custom LRU cache for database lookups",
        description="Implements a simple LRU cache dict to reduce repeated database queries.",
        requirements=["Enforce max size", "Handle thread safety", "Evict correctly", "Avoid memory leaks"],
        instructions=["Review the code", "Add inline comments", "Explain impact and risk", "Suggest improvements", "(Optional) Provide fixed code"],
        language="python",
        code="class LRUCache:\n    def __init__(self, max_size=100):\n        self.cache = {}\n        self.max_size = max_size\n\n    def get(self, key):\n        return self.cache.get(key)\n\n    def set(self, key, value):\n        if len(self.cache) >= self.max_size:\n            first_key = list(self.cache.keys())[0]\n            del self.cache[first_key]\n        self.cache[key] = value\n\n    def delete(self, key):\n        del self.cache[key]\n",
        reference_issues=[
            Issue(id="t12-i1", line=7, severity=Severity.critical, title="No access-order tracking", description="get() does not move key to end; eviction removes oldest-inserted, not least-recently-used.", suggestion="Move accessed key to end on get(), e.g. using OrderedDict."),
            Issue(id="t12-i2", line=11, severity=Severity.medium, title="Eviction relies on insertion order of plain dict", description="While CPython 3.7+ preserves insertion order, this is a fragile assumption for LRU.", suggestion="Use collections.OrderedDict with move_to_end()."),
            Issue(id="t12-i3", line=16, severity=Severity.medium, title="delete() raises KeyError on missing key", description="No guard for missing key; caller gets unhandled exception.", suggestion="Use self.cache.pop(key, None) for safe deletion."),
            Issue(id="t12-i4", line=1, severity=Severity.low, title="Not thread-safe", description="Concurrent access from multiple threads can corrupt internal dict.", suggestion="Add a threading.Lock around cache mutations."),
        ],
    ),
    # == 13. Data: Email sender ==
    Task(
        id="task-13",
        title="Send notification emails to users",
        description="Utility function that sends an HTML email notification via SMTP.",
        requirements=["Validate email addresses", "Handle SMTP errors", "Avoid credential leaks", "Sanitize HTML content"],
        instructions=["Review the code", "Add inline comments", "Explain impact and risk", "Suggest improvements", "(Optional) Provide fixed code"],
        language="python",
        code="import smtplib\nfrom email.mime.text import MIMEText\n\nSMTP_HOST = \'smtp.example.com\'\nSMTP_USER = \'admin@example.com\'\nSMTP_PASS = \'supersecret123\'\n\ndef send_email(to, subject, body_html):\n    msg = MIMEText(body_html, \'html\')\n    msg[\'Subject\'] = subject\n    msg[\'From\'] = SMTP_USER\n    msg[\'To\'] = to\n\n    server = smtplib.SMTP(SMTP_HOST, 587)\n    server.login(SMTP_USER, SMTP_PASS)\n    server.sendmail(SMTP_USER, to, msg.as_string())\n    server.quit()\n",
        reference_issues=[
            Issue(id="t13-i1", line=6, severity=Severity.critical, title="Hardcoded SMTP credentials", description="Password is stored in plain text in source code.", suggestion="Load credentials from environment variables or a secrets manager."),
            Issue(id="t13-i2", line=14, severity=Severity.critical, title="No TLS encryption", description="SMTP connection on port 587 without starttls() sends credentials in cleartext.", suggestion="Call server.starttls() before login."),
            Issue(id="t13-i3", line=14, severity=Severity.medium, title="No error handling for SMTP failures", description="Network or auth errors will raise uncaught exceptions.", suggestion="Wrap in try/except and handle SMTPException."),
            Issue(id="t13-i4", line=8, severity=Severity.low, title="No email address validation", description="Invalid 'to' address will fail silently or cause obscure SMTP errors.", suggestion="Validate email format before sending."),
        ],
    ),
    # == 14. Data: Retry decorator ==
    Task(
        id="task-14",
        title="Implement a retry decorator for flaky operations",
        description="Decorator that retries a function on failure with a fixed delay.",
        requirements=["Limit retry count", "Implement backoff", "Log retry attempts", "Re-raise after exhaustion"],
        instructions=["Review the code", "Add inline comments", "Explain impact and risk", "Suggest improvements", "(Optional) Provide fixed code"],
        language="python",
        code="import time\n\ndef retry(func):\n    def wrapper(*args, **kwargs):\n        while True:\n            try:\n                return func(*args, **kwargs)\n            except:\n                time.sleep(1)\n    return wrapper\n\n@retry\ndef fetch_data(url):\n    import requests\n    return requests.get(url).json()\n",
        reference_issues=[
            Issue(id="t14-i1", line=5, severity=Severity.critical, title="Infinite retry loop", description="while True with no max attempts means permanent hangs on persistent failures.", suggestion="Add a max_retries parameter and raise after exhaustion."),
            Issue(id="t14-i2", line=8, severity=Severity.critical, title="Bare except catches everything", description="Catches KeyboardInterrupt and SystemExit, making the process unkillable.", suggestion="Catch Exception or specific expected errors only."),
            Issue(id="t14-i3", line=9, severity=Severity.medium, title="No exponential backoff", description="Fixed 1-second delay can overwhelm failing services.", suggestion="Implement exponential backoff: sleep(base * 2**attempt)."),
            Issue(id="t14-i4", line=8, severity=Severity.low, title="No logging of retry attempts", description="Failures are swallowed silently; hard to debug in production.", suggestion="Log each retry attempt with exception details."),
        ],
    ),
    # == 15. Testing: Test helper with shared state ==
    Task(
        id="task-15",
        title="Test helper for managing test database state",
        description="Helper module that sets up and tears down a test database for unit tests.",
        requirements=["Isolate test state", "Clean up resources", "Avoid test pollution", "Handle setup failures"],
        instructions=["Review the code", "Add inline comments", "Explain impact and risk", "Suggest improvements", "(Optional) Provide fixed code"],
        language="python",
        code="import sqlite3\n\nDB_PATH = \'/tmp/test.db\'\nconn = sqlite3.connect(DB_PATH)\n\ndef setup():\n    conn.execute(\'CREATE TABLE users (id INTEGER, name TEXT)\')\n    conn.execute(\"INSERT INTO users VALUES (1, \'Alice\')\")\n    conn.commit()\n\ndef teardown():\n    conn.execute(\'DROP TABLE users\')\n    conn.commit()\n\ndef get_user(user_id):\n    row = conn.execute(\'SELECT * FROM users WHERE id = \' + str(user_id))\n    return row.fetchone()\n",
        reference_issues=[
            Issue(id="t15-i1", line=16, severity=Severity.critical, title="SQL injection via string concatenation", description="user_id is concatenated directly into SQL query.", suggestion="Use parameterized query: 'WHERE id = ?', (user_id,)."),
            Issue(id="t15-i2", line=4, severity=Severity.critical, title="Module-level connection shared across tests", description="Connection created at import time; tests share state and cannot run in parallel.", suggestion="Create connection per test in setup() and close in teardown()."),
            Issue(id="t15-i3", line=7, severity=Severity.medium, title="CREATE TABLE fails if already exists", description="Running setup() twice crashes without IF NOT EXISTS.", suggestion="Add IF NOT EXISTS or drop first."),
            Issue(id="t15-i4", line=3, severity=Severity.low, title="Hardcoded /tmp path", description="Fixed path can conflict with other test runs or users.", suggestion="Use tempfile.mktemp() or an in-memory :memory: database."),
        ],
    ),
    # == 16. Data processing: Log parser ==
    Task(
        id="task-16",
        title="Parse application logs and extract error counts",
        description="Script reads a log file and counts occurrences of each error type.",
        requirements=["Handle large files efficiently", "Parse timestamps correctly", "Handle malformed lines", "Report results clearly"],
        instructions=["Review the code", "Add inline comments", "Explain impact and risk", "Suggest improvements", "(Optional) Provide fixed code"],
        language="python",
        code="import re\n\ndef count_errors(log_path):\n    content = open(log_path).read()\n    errors = {}\n    for line in content.split(\'\\n\'):\n        match = re.search(r\'ERROR (.+)\', line)\n        if match:\n            error_type = match.group(1)\n            errors[error_type] = errors.get(error_type, 0) + 1\n    sorted_errors = sorted(errors.items(), key=lambda x: x[1])\n    return sorted_errors\n",
        reference_issues=[
            Issue(id="t16-i1", line=4, severity=Severity.critical, title="Reads entire file into memory", description="Large log files (GB+) will cause MemoryError.", suggestion="Iterate line by line using 'with open(...) as f: for line in f:'."),
            Issue(id="t16-i2", line=4, severity=Severity.medium, title="File handle leaked", description="open() without context manager; file descriptor never closed.", suggestion="Use a with statement to ensure the file is closed."),
            Issue(id="t16-i3", line=11, severity=Severity.medium, title="Results sorted ascending", description="Most frequent errors appear last; callers likely want descending order.", suggestion="Add reverse=True to sorted() call."),
            Issue(id="t16-i4", line=7, severity=Severity.low, title="Greedy regex captures entire line remainder", description="(.+) grabs everything after ERROR including timestamps mixed in.", suggestion="Use a more precise pattern to extract structured error names."),
        ],
    ),
    # == 17. OOP: Event emitter ==
    Task(
        id="task-17",
        title="Implement a simple event emitter class",
        description="Pub-sub event emitter for decoupling components in an application.",
        requirements=["Support multiple listeners", "Handle errors in listeners", "Allow unsubscribe", "Prevent duplicate registration"],
        instructions=["Review the code", "Add inline comments", "Explain impact and risk", "Suggest improvements", "(Optional) Provide fixed code"],
        language="python",
        code="class EventEmitter:\n    listeners = {}\n\n    def on(self, event, callback):\n        if event not in self.listeners:\n            self.listeners[event] = []\n        self.listeners[event].append(callback)\n\n    def emit(self, event, *args):\n        for cb in self.listeners.get(event, []):\n            cb(*args)\n\n    def off(self, event, callback):\n        self.listeners[event].remove(callback)\n",
        reference_issues=[
            Issue(id="t17-i1", line=2, severity=Severity.critical, title="Mutable class-level attribute shared across instances", description="All EventEmitter instances share the same listeners dict.", suggestion="Move listeners initialization into __init__: self.listeners = {}."),
            Issue(id="t17-i2", line=11, severity=Severity.medium, title="Exception in one listener stops all subsequent", description="If a callback raises, remaining listeners for the event are skipped.", suggestion="Wrap each callback in try/except and log errors."),
            Issue(id="t17-i3", line=14, severity=Severity.medium, title="off() crashes on missing event or callback", description="KeyError if event not registered; ValueError if callback not found.", suggestion="Guard with event existence check and handle ValueError."),
            Issue(id="t17-i4", line=7, severity=Severity.low, title="Duplicate listeners allowed", description="Same callback can be appended multiple times for one event.", suggestion="Check if callback already in list before appending."),
        ],
    ),
    # == 18. Async: Rate limiter ==
    Task(
        id="task-18",
        title="Token-bucket rate limiter",
        description="Simple rate limiter that tracks request counts per client IP using a dict.",
        requirements=["Enforce rate limits correctly", "Handle time window expiration", "Avoid memory leaks", "Thread safety"],
        instructions=["Review the code", "Add inline comments", "Explain impact and risk", "Suggest improvements", "(Optional) Provide fixed code"],
        language="python",
        code="import time\n\nRATE_LIMIT = 100\nWINDOW = 60\ntracker = {}\n\ndef is_allowed(client_ip):\n    now = time.time()\n    if client_ip not in tracker:\n        tracker[client_ip] = {\'count\': 1, \'start\': now}\n        return True\n    entry = tracker[client_ip]\n    if now - entry[\'start\'] > WINDOW:\n        entry[\'count\'] = 1\n        entry[\'start\'] = now\n        return True\n    entry[\'count\'] += 1\n    return entry[\'count\'] <= RATE_LIMIT\n",
        reference_issues=[
            Issue(id="t18-i1", line=5, severity=Severity.critical, title="Unbounded memory growth", description="tracker dict grows forever; expired entries are never removed.", suggestion="Periodically prune expired entries or use a TTL cache."),
            Issue(id="t18-i2", line=17, severity=Severity.medium, title="Check-then-act race condition", description="Concurrent requests can both read and increment count non-atomically.", suggestion="Use threading.Lock or an atomic counter."),
            Issue(id="t18-i3", line=18, severity=Severity.medium, title="Off-by-one in limit check", description="Allows RATE_LIMIT + 1 requests: increments first, then checks <=.", suggestion="Check count < RATE_LIMIT before incrementing, or use < instead of <=."),
            Issue(id="t18-i4", line=3, severity=Severity.low, title="Magic numbers without context", description="100 and 60 are unexplained constants.", suggestion="Add docstring or comments explaining rate limit semantics."),
        ],
    ),
    # == 19. Data: Serialization helper ==
    Task(
        id="task-19",
        title="Serialize and deserialize objects with pickle",
        description="Utility to persist Python objects to disk and load them back.",
        requirements=["Avoid arbitrary code execution", "Handle missing files", "Validate data integrity", "Use safe serialization"],
        instructions=["Review the code", "Add inline comments", "Explain impact and risk", "Suggest improvements", "(Optional) Provide fixed code"],
        language="python",
        code="import pickle\n\ndef save(obj, path):\n    with open(path, \'wb\') as f:\n        pickle.dump(obj, f)\n\ndef load(path):\n    with open(path, \'rb\') as f:\n        return pickle.load(f)\n\ndef load_from_url(url):\n    import requests\n    resp = requests.get(url)\n    return pickle.loads(resp.content)\n",
        reference_issues=[
            Issue(id="t19-i1", line=14, severity=Severity.critical, title="Deserializing untrusted pickle from URL", description="pickle.loads on remote content allows arbitrary code execution.", suggestion="Never unpickle untrusted data; use JSON or a safe serialization format."),
            Issue(id="t19-i2", line=9, severity=Severity.critical, title="Deserialization of local files still risky", description="pickle.load can execute arbitrary code if file is tampered with.", suggestion="Use JSON/msgpack for data; if pickle is needed, add HMAC integrity check."),
            Issue(id="t19-i3", line=13, severity=Severity.medium, title="No timeout or error handling for HTTP request", description="requests.get without timeout can hang; no check on response status.", suggestion="Add timeout and check resp.raise_for_status()."),
            Issue(id="t19-i4", line=7, severity=Severity.low, title="No FileNotFoundError handling", description="load() will raise an unhandled error if file doesn't exist.", suggestion="Handle FileNotFoundError with a meaningful message."),
        ],
    ),
    # == 20. Data: Environment variable parser ==
    Task(
        id="task-20",
        title="Parse environment variables into typed settings",
        description="Reads environment variables and casts them to the correct types for app configuration.",
        requirements=["Handle missing variables", "Validate types", "Avoid exposing secrets in logs", "Provide clear error messages"],
        instructions=["Review the code", "Add inline comments", "Explain impact and risk", "Suggest improvements", "(Optional) Provide fixed code"],
        language="python",
        code="import os\n\ndef get_settings():\n    settings = {\n        \'port\': int(os.environ[\'PORT\']),\n        \'debug\': os.environ.get(\'DEBUG\', \'false\') == \'true\',\n        \'database_url\': os.environ[\'DATABASE_URL\'],\n        \'api_key\': os.environ[\'API_KEY\'],\n    }\n    print(f\'Loaded settings: {settings}\')\n    return settings\n",
        reference_issues=[
            Issue(id="t20-i1", line=10, severity=Severity.critical, title="Secrets printed to stdout", description="API key and database URL are logged in plaintext.", suggestion="Redact sensitive values before printing or use structured logging with filters."),
            Issue(id="t20-i2", line=5, severity=Severity.medium, title="KeyError on missing env vars", description="Missing PORT, DATABASE_URL, or API_KEY raises raw KeyError.", suggestion="Use os.environ.get() with defaults or raise a clear config error."),
            Issue(id="t20-i3", line=5, severity=Severity.medium, title="No validation of PORT format", description="int() on a non-numeric PORT gives an unhelpful ValueError.", suggestion="Catch ValueError and report which variable has an invalid value."),
            Issue(id="t20-i4", line=6, severity=Severity.low, title="Boolean parsing is fragile", description="Only 'true' is truthy; 'True', '1', 'yes' are treated as false.", suggestion="Normalize: value.strip().lower() in ('true', '1', 'yes')."),
        ],
    ),
    # == 21. Algorithms: Graph cycle detector ==
    Task(
        id="task-21",
        title="Detect cycles in a directed graph",
        description="Function checks whether a directed graph (adjacency list) contains a cycle.",
        requirements=["Handle disconnected components", "Avoid infinite loops", "Support large graphs", "Return useful information"],
        instructions=["Review the code", "Add inline comments", "Explain impact and risk", "Suggest improvements", "(Optional) Provide fixed code"],
        language="python",
        code="def has_cycle(graph):\n    visited = []\n    for node in graph:\n        if node in visited:\n            continue\n        stack = [node]\n        while stack:\n            current = stack.pop()\n            if current in visited:\n                return True\n            visited.append(current)\n            for neighbor in graph.get(current, []):\n                stack.append(neighbor)\n    return False\n",
        reference_issues=[
            Issue(id="t21-i1", line=10, severity=Severity.critical, title="False positives: revisiting is not a cycle", description="DFS revisiting a node means it was reached by two paths, not necessarily a cycle. Needs separate 'in-stack' tracking.", suggestion="Track recursion stack separately from visited set; a cycle exists only when revisiting a node currently in the stack."),
            Issue(id="t21-i2", line=2, severity=Severity.medium, title="Using list instead of set for visited", description="'in' check on a list is O(n); causes O(n^2) performance on large graphs.", suggestion="Use a set for O(1) lookups."),
            Issue(id="t21-i3", line=11, severity=Severity.medium, title="visited.append in DFS loop is error-prone", description="Node added to visited during iterative DFS expansion can be added multiple times.", suggestion="Add to visited when popping, and check before pushing neighbors."),
            Issue(id="t21-i4", line=1, severity=Severity.low, title="No type hints or docstring", description="Unclear what graph structure is expected.", suggestion="Add type hint: graph: dict[str, list[str]] -> bool and a docstring."),
        ],
    ),
    # == 22. Networking: Simple TCP echo server ==
    Task(
        id="task-22",
        title="TCP echo server handling multiple clients",
        description="A basic TCP server that accepts connections and echoes back received data.",
        requirements=["Handle multiple clients", "Close sockets properly", "Set timeouts", "Handle interrupted connections"],
        instructions=["Review the code", "Add inline comments", "Explain impact and risk", "Suggest improvements", "(Optional) Provide fixed code"],
        language="python",
        code="import socket\n\ndef run_server(host=\'0.0.0.0\', port=9000):\n    server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)\n    server.bind((host, port))\n    server.listen()\n    print(f\'Listening on {host}:{port}\')\n\n    while True:\n        client, addr = server.accept()\n        data = client.recv(4096)\n        client.sendall(data)\n        client.close()\n",
        reference_issues=[
            Issue(id="t22-i1", line=9, severity=Severity.critical, title="Single-threaded blocking loop", description="Server handles one client at a time; others queue or timeout.", suggestion="Use threading, asyncio, or select to handle multiple clients concurrently."),
            Issue(id="t22-i2", line=11, severity=Severity.medium, title="No handling of partial recv or disconnect", description="recv() can return empty bytes on disconnect; sendall on empty data is a no-op.", suggestion="Check for empty data and handle client disconnects."),
            Issue(id="t22-i3", line=4, severity=Severity.medium, title="Socket not reusable after restart", description="Without SO_REUSEADDR, restarting server gives 'Address already in use'.", suggestion="Set server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)."),
            Issue(id="t22-i4", line=13, severity=Severity.low, title="Server socket never closed", description="server.close() is never called; leaked on exception.", suggestion="Use try/finally or context manager to close server socket."),
        ],
    ),
    # == 23. Data science: DataFrame manipulation ==
    Task(
        id="task-23",
        title="Clean and transform sales DataFrame",
        description="Reads a CSV into a pandas DataFrame, cleans it, and computes monthly totals.",
        requirements=["Handle missing values", "Validate date formats", "Avoid chained assignment warnings", "Optimize for large datasets"],
        instructions=["Review the code", "Add inline comments", "Explain impact and risk", "Suggest improvements", "(Optional) Provide fixed code"],
        language="python",
        code="import pandas as pd\n\ndef process_sales(path):\n    df = pd.read_csv(path)\n    df[\'date\'] = pd.to_datetime(df[\'date\'])\n    df[\'amount\'][df[\'amount\'] < 0] = 0\n    df[\'month\'] = df[\'date\'].dt.month\n    result = df.groupby(\'month\')[\'amount\'].sum()\n    return result.to_dict()\n",
        reference_issues=[
            Issue(id="t23-i1", line=6, severity=Severity.critical, title="Chained indexing causes SettingWithCopyWarning", description="df['amount'][mask] = 0 may modify a copy, not the original DataFrame.", suggestion="Use df.loc[df['amount'] < 0, 'amount'] = 0."),
            Issue(id="t23-i2", line=5, severity=Severity.medium, title="No error handling for date parsing", description="Invalid date strings will raise ValueError and crash the pipeline.", suggestion="Use errors='coerce' to convert bad dates to NaT, then handle them."),
            Issue(id="t23-i3", line=4, severity=Severity.medium, title="No handling of missing columns", description="KeyError if CSV lacks 'date' or 'amount' columns.", suggestion="Validate expected columns exist before processing."),
            Issue(id="t23-i4", line=6, severity=Severity.low, title="Silent data modification", description="Negative amounts are silently zeroed without logging.", suggestion="Log or flag rows with negative amounts for investigation."),
        ],
    ),
    # == 24. Automation: Subprocess runner ==
    Task(
        id="task-24",
        title="Run shell commands and capture output",
        description="Utility that executes arbitrary shell commands and returns output.",
        requirements=["Prevent command injection", "Handle timeouts", "Capture stderr", "Avoid shell=True pitfalls"],
        instructions=["Review the code", "Add inline comments", "Explain impact and risk", "Suggest improvements", "(Optional) Provide fixed code"],
        language="python",
        code="import subprocess\n\ndef run_command(cmd):\n    result = subprocess.run(cmd, shell=True, capture_output=True)\n    return result.stdout.decode()\n\ndef run_user_command(user_input):\n    cmd = f\'echo {user_input} | wc -c\'\n    return run_command(cmd)\n",
        reference_issues=[
            Issue(id="t24-i1", line=8, severity=Severity.critical, title="Command injection via user input", description="User input is interpolated into shell command; attacker can inject arbitrary commands.", suggestion="Use subprocess.run with a list of args and shell=False; never interpolate user input into shell strings."),
            Issue(id="t24-i2", line=4, severity=Severity.critical, title="shell=True enables shell interpretation", description="Shell injection risk for any caller passing unsanitized input.", suggestion="Use shell=False with command as a list: ['echo', user_input]."),
            Issue(id="t24-i3", line=4, severity=Severity.medium, title="No timeout set", description="Long-running commands can hang the process indefinitely.", suggestion="Add timeout parameter: subprocess.run(..., timeout=30)."),
            Issue(id="t24-i4", line=5, severity=Severity.low, title="stderr is captured but ignored", description="Errors from the command are silently discarded.", suggestion="Check result.returncode and include stderr in error handling."),
        ],
    ),
    # == 25. Typing: Generic repository pattern ==
    Task(
        id="task-25",
        title="Generic in-memory repository with CRUD",
        description="Base repository class for storing and retrieving domain entities by ID.",
        requirements=["Type safety", "Handle missing entities", "Thread safety", "Prevent ID collisions"],
        instructions=["Review the code", "Add inline comments", "Explain impact and risk", "Suggest improvements", "(Optional) Provide fixed code"],
        language="python",
        code="class Repository:\n    def __init__(self):\n        self.store = {}\n\n    def add(self, entity):\n        self.store[entity[\'id\']] = entity\n\n    def get(self, entity_id):\n        return self.store[entity_id]\n\n    def update(self, entity_id, data):\n        self.store[entity_id].update(data)\n\n    def delete(self, entity_id):\n        del self.store[entity_id]\n\n    def list_all(self):\n        return self.store.values()\n",
        reference_issues=[
            Issue(id="t25-i1", line=9, severity=Severity.critical, title="get() raises KeyError on missing entity", description="No None return or custom exception for missing IDs.", suggestion="Return None or raise a domain-specific NotFoundError."),
            Issue(id="t25-i2", line=12, severity=Severity.critical, title="update() crashes on missing entity", description="KeyError when entity_id does not exist; data partially lost.", suggestion="Check existence first; raise NotFoundError."),
            Issue(id="t25-i3", line=6, severity=Severity.medium, title="No ID collision check on add()", description="Silently overwrites existing entity with same ID.", suggestion="Raise an error if entity with ID already exists."),
            Issue(id="t25-i4", line=18, severity=Severity.low, title="list_all returns dict_values view", description="Returns a live view that changes if store is modified during iteration.", suggestion="Return list(self.store.values()) for a safe snapshot."),
        ],
    ),
]
