"""Agents module - AI agents for code review and answer evaluation."""

from app.agents.ai_analyzer import analyze_review
from app.agents.prompts import (
    CODE_REVIEW_EVALUATION_RULES,
    CODE_REVIEW_SYSTEM_PROMPT,
    DEFAULT_OLLAMA_BASE_URL,
    DEFAULT_OLLAMA_MODEL,
    DEFAULT_TEMPERATURE,
    DEFAULT_TIMEOUT_SECONDS,
    OUTPUT_SCHEMA_CODE_REVIEW,
    OUTPUT_SCHEMA_THEORY_ANSWER,
    THEORY_ANSWER_EVALUATION_RULES,
    THEORY_ANSWER_SYSTEM_PROMPT,
)

__all__ = [
    "analyze_review",
    "CODE_REVIEW_EVALUATION_RULES",
    "CODE_REVIEW_SYSTEM_PROMPT",
    "DEFAULT_OLLAMA_BASE_URL",
    "DEFAULT_OLLAMA_MODEL",
    "DEFAULT_TEMPERATURE",
    "DEFAULT_TIMEOUT_SECONDS",
    "OUTPUT_SCHEMA_CODE_REVIEW",
    "OUTPUT_SCHEMA_THEORY_ANSWER",
    "THEORY_ANSWER_EVALUATION_RULES",
    "THEORY_ANSWER_SYSTEM_PROMPT",
]
